### ISSUE TITLE
APs scan issue

### ISSUE THREAD

**Issue by TwinkleFredrik** [spacehuhn/esp8266_deauther#62]
I had a working board that worked flawlessly with the "master" version.. but after giving the "esp8266_deauther-testing" version a try the only message I get now when trying to scan for APs is
![image](https://cloud.githubusercontent.com/assets/5722293/23534185/72500274-ffb6-11e6-8e7e-0121d28d79b2.png)
(even after switching back to master version)

I do not understand what has happened?

**Comment by poslogic** [comment]
Disable/forget your home network so that the phone/PC (device you are using) can only automatically connect to the board.

**Comment by TwinkleFredrik** [comment]
The device I am using to connect to it has none remembered so that is not the problem.. It is connected but after failing a couple of times my device becomes disconnected.

**Comment by poslogic** [comment]
Flash a simple blink sketch to your board, then try removing and rebooting your PC.

Then try re- flashing the master branch that works well for you.

Hope this helps.

**Comment by TwinkleFredrik** [comment]
I uploaded 
![image](https://cloud.githubusercontent.com/assets/5722293/23534566/14994804-ffb9-11e6-9768-298c5731c4bb.png)
This script works BUT... The other one seems to be running as well in the background? The old ssid I chose and password pops up in my wifi list.

**Comment by TwinkleFredrik** [comment]
I tried to upload the master version again but problem still coexists :(

**Comment by tpmodding** [comment]
no infos...which phone? which browser? 

I connect to my NodeMCU with my iPhone 6, if I scan AP's it does not disconnect, but if i scan for clients, my iphone disconnects, cause the esp scans, in this time my phone connects to my local router -> so i have to reconnect to my nodemcu, than it shows me the clients

**Comment by TwinkleFredrik** [comment]
@tpmodding you must have misunderstood... I am not using any phone and it would be irrelevant when I have already tested on sevral browsers and devices. Nothing says the iphone is better at connecting to the internet compared to any android that may be more intelligent. and if you are wondering.. No, I am not using internet explorer....

**Comment by poslogic** [comment]
Try clearing browse cache and cookies.

**Comment by TwinkleFredrik** [comment]
no progress.. same issue

**Comment by tpmodding** [comment]
just wanted to help and you give me a thumbs down? you say you are not using IE but dont say which one you use... no info, no support

**Comment by TwinkleFredrik** [comment]
@tpmodding Just told you I try what I can.. Chrome, Opera, firefox, safari, chromium and edge. happy?

**Comment by TwinkleFredrik** [comment]
Update: If it has something to do with it, the webserver crashes and turns everything white when I click the clients tab

**Comment by joneroy** [comment]
@TwinkleFredrik i think it's a bug on ap.html #51 press hastag check the prob and say it's same prob or not

**Comment by TwinkleFredrik** [comment]
@joneroy No my problem does not seem to be related to #51 The only error message I get is the one you see on the first post. The page loads just fine and everything seems to work but when I press scan on the APs tab the esp8266 crashes and gives me that until I unplug it from power.

**Comment by TwinkleFredrik** [comment]
@spacehuhn what is this duplicate to?

**Comment by spacehuhn** [comment]
#5

**Comment by joneroy** [comment]
@TwinkleFredrik you are using testing branch or not so you are not using testing branch use it no bug found everything solved by @spacehuhn

**Comment by joneroy** [comment]
@spacehuhn 

# **close this issue it's solved**

**Comment by TwinkleFredrik** [comment]
But its not solved when my board isnt working propperly and I dont know what to do other than searching around to finally find the solution somewhere on this page :/

**Comment by TwinkleFredrik** [comment]
Or has it recently been updated and I need to download both of the versions and try again?

**Comment by joneroy** [comment]
@TwinkleFredrik Download both of the versions and try again.

**Comment by tobozo** [comment]
@TwinkleFredrik also check the recent changes in the ReadMe

**Comment by joneroy** [comment]
@spacehuhn 

# **close this issue it's solved**

**Comment by TwinkleFredrik** [comment]
I tried the updated master build.. got this: Arduino: 1.8.1 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

sketch\APScan.cpp: In member function 'bool APScan::start()':

APScan.cpp:14: error: no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

     results = WiFi.scanNetworks(false, settings.apScanHidden); // lets scanNetworks return hidden APs. (async = false & show_hidden = true)

                                                             ^

sketch\APScan.cpp:14:61: note: candidate is:

In file included from sketch\APScan.h:6:0,

                 from sketch\APScan.cpp:1:

C:\Users\Twinkle-Fredrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note: int8_t ESP8266WiFiClass::scanNetworks(bool)

     int8_t scanNetworks(bool async = false);

            ^

C:\Users\Twinkle-Fredrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:243:12: note:   candidate expects 1 argument, 2 provided

exit status 1
no matching function for call to 'ESP8266WiFiClass::scanNetworks(bool, bool&)'

**Comment by TwinkleFredrik** [comment]
Should I just open a new issue post with the comment above? This is during compilation..

**Comment by spacehuhn** [comment]
> @TwinkleFredrik also check the recent changes in the ReadMe

People trying to help you, just listen to them and your problem is solved.

**Comment by TwinkleFredrik** [comment]
But how do I find the recent changes? I search for recent changes but cant find out what is different with the readme file.

**Comment by spacehuhn** [comment]
dude... read the readme!

**Comment by joneroy** [comment]
@TwinkleFredrik 

https://github.com/spacehuhn/esp8266_deauther/blob/master/README.md

**Comment by TwinkleFredrik** [comment]
Thank you @joneroy finally works again! :)
You really are good at helping.
